### ISSUE TITLE
Cannot open negative fits file 

### ISSUE THREAD

**Issue by diedie9** [soedinglab/WIsH#10]
Hello.
When I run Wish, I get an error message. 

steps: 6/6 “start” Tue Jun 14 10:18:26 CEST 2022
ERROR:Cannot open negative fits file /work/hudi/LINA-1/vir/wish/Co1-113K_/nullmodels/nullParameters.tsv.
steps: 6/6 Tue Jun 14 10:18:28 CEST 2022

How to deal with it?
Thanks very much

**Comment by ClovisG** [comment]
Hi,
Thanks for your interest in our tool. 

Please give more details: Do you use WIsH with Linux? as a Docker?
Do you have access to the file "/work/hudi/LINA-1/vir/wish/Co1-113K_/nullmodels/nullParameters.tsv"? You can run the following command to check it:

`head /work/hudi/LINA-1/vir/wish/Co1-113K_/nullmodels/nullParameters.tsv`

If the file does not exist, you need either to generate this file look [here](https://github.com/soedinglab/WIsH#getting-the-null-paramters-for-new-bacterial-models), or run a prediction without p-values generation (i.e. without the -p parameter).

Let me know if you have any further issue.
Clovis.

**Comment by diedie9** [comment]
Hi Clovis,
Thanks for your reply.


I use the bash to run WIsH in Linux.


yes, I can access /work/hudi/LINA-1/vir/wish/Co1-113K_/nullmodels/nullParameters.tsv.
And there are some message

NG-28519_LINA00523K_lib514357_7846_4_-bin.68    -1.40601326823665    0.0108027997691293
Co1-174K_-bin.65    -1.41437800689259    0.0118836231083342
Co1-598K_-bin.60    -1.40846612291786    0.0267099254999412
Co1-413K_-bin.34    -1.40504311889719    0.0366269946237823
NG-28519_LINA00414K_lib514340_7864_3_-bin.23    -1.41054054566341    0.0373640263907783
NG-28519_LINA00089K_lib527733_7846_4_-bin.1    -1.41061645031591    0.0231964196444687
Co1-213K_-bin.28    -1.40875699310741    0.0287130567940117
Co1-205K_-bin.84    -1.40660014646755    0.0312217646568303
NG-28519_LINA00182K_lib514335_7886_3_-bin.31    -1.41177971280873    0.0150262898152293
NG-28519_LINA00522K_lib514347_7886_3_-bin.57    -1.39917443136129    0.0146365160056128


So I am so strange that message.


What else details you want to know?


Kind regards,
Die


At 2022-06-14 11:15:21, "ClovisG" ***@***.***> wrote:

Hi,
Thanks for your interest in our tool.

Please give more details: Do you use WIsH with Linux? as a Docker?
Do you have access to the file "/work/hudi/LINA-1/vir/wish/Co1-113K_/nullmodels/nullParameters.tsv"? You can run the following command to check it:

head /work/hudi/LINA-1/vir/wish/Co1-113K_/nullmodels/nullParameters.tsv

If the file does not exist, you need either to generate this file look here, or run a prediction without p-values generation (i.e. without the -p parameter).

Let me know if you have any further issue.
Clovis.

**Comment by ClovisG** [comment]
Hi,
There should be something wrong with the file access.  I suggest that you put temporarily the null model parameters file into a simpler path (for instance /tmp/null.tsv) and see if it works (I suspect that the "-" and "_" of the path may interfere weirdly).

If this does not work, you may create an archive with one or two examples reproducing the bug of your phage+model+null models and send me by email so that I can see if I get the same error.

Best,
Clovis.

**Comment by diedie9** [comment]
Hi,
I run it with my simpler path, but it also has the same error message
steps: 6/6 “start” Tue Jun 14 16:49:18 CEST 2022
ERROR:Cannot open negative fits file /work/hudi/nullmodels/nullParameters.tsv.
steps: 6/6 Tue Jun 14 16:49:22 CEST 2022




There are 2 .fna files attached.


Please help me to check it.





Kind regards,
Die





在 2022-06-14 15:15:15，"ClovisG" ***@***.***> 写道：

Hi,
There should be something wrong with the file access. I suggest that you put temporarily the null model parameters file into a simpler path (for instance /tmp/null.tsv) and see if it works (I suspect that the "-" and "_" of the path may interfere weirdly).

If this does not work, you may create an archive with one or two examples reproducing the bug of your phage+model+null models and send me by email so that I can see if I get the same error.

Best,
Clovis.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

从网易163邮箱发来的超大附件
viruses_test_by _wish.tar.xz (14.82M, 2022年6月29日 17:09 到期)
下载

**Comment by ClovisG** [comment]
Have you solved your issue?
If not could you report me the exact command you use to run the prediction? Are you using the Docker version?

**Comment by ClovisG** [comment]
I'll set the flag to closed, don't hesitate to re-open it.
